# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JVFloatLabeledTextField_Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JVFloatLabeledTextField_Example

  target 'JVFloatLabeledTextField_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JVFloatLabeledTextField_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_frameworks!

  pod 'JVFloatLabeledTextField'

end
